### ISSUE TITLE
Hi @Brainhack-Global/project-monitors: my project is ready!

### ISSUE THREAD

**Issue by Paris-Lyons** [brainhackorg/global2021#136]
Hi @Brainhack-Global/project-monitors: my project is ready!

**Comment by Remi-Gau** [comment]
ha I think our instructions were not clear enough : what we meant was to add a comment below your issue like I just did here:

https://github.com/brainhackorg/global2021/issues/128#issuecomment-979775177

Will update the submission template to try to avoid confusions down the line.

Will close this issue in the meantime: sorry @Paris-Lyons for the confusion.
