### ISSUE TITLE
Code of conduct page ?

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2021#18]
There is some content  oin the CoC folder `https://github.com/brainhackorg/global2021/tree/main/content/code-of-conduct` but most of it is commented and the the link in the NavBar links to the brainhack main wesbite CoC.

Is that some work in progress from last year ? @complexbrains @SamGuay 

Shouldn't this commented code be better in a separate branch if it is work in progress? Commented code or content is usually more confusing than anything else.

**Comment by SamGuay** [comment]
To make a long story short, we had a plan, but the plan was revised to link to the central BH's CoC and each event would have to follow their own institution's CoC, given laws are different based on countries, etc..

But you are right, it shouldn't be on the main brain. A lot can be cleaned from it actually..

**Comment by Remi-Gau** [comment]
closing this as the WIP CoC as been moved to #36
