### ISSUE TITLE
Update FAQ 

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2021#27]
Update the FAQ as move along with the new updates regarding project submissions and all.

**Comment by complexbrains** [comment]
FAQ seems up to date with the dates, will issue there if there will be any other features needed to be mention this year.

**Comment by Remi-Gau** [comment]
Should we close this for now then?

**Comment by complexbrains** [comment]
I guess we can! I will make the additions in the meantime if there will be any needed! Thank you!
