### ISSUE TITLE
Improve art gallery

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2021#49]
Possible improvements are:

- the gallery
  - add some more intro text ?
- the footer: 
  - centering the different <div>
  - fix the link to the art  gallery: currently https://brainhack.org/global2021/TODO
  - change the font color for the links: they are really hard to see compare to the normal text 
- the choice of art for each section:
  - for the main page I have chosen what "looked" good to me, but I am definitely not the best at this. Suggestions welcome.

**Comment by vborghe** [comment]
I think your selection looks great (and I am not sure I can help with the footer)- but maybe as soon as the BrainArt SIG posts its revised preprint I could add it (with a couple of words more) to the intro text?

**Comment by Remi-Gau** [comment]
closing old issues of mine
