### ISSUE TITLE
Update issue template to use the "form" format ?

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2021#5]
I suspect this could definitely help project and new site submission.

What do you think?

See here:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

https://www.youtube.com/watch?v=qQE1BUkf2-s

**Comment by complexbrains** [comment]
Amazing idea! I watched it back in the time you shared. Let me assign this to myself and work on it to ask your review for then!

**Comment by Remi-Gau** [comment]
This will most lilely require to update the python code that was used to generate the project pages but hopefully the forms will help us parse the issue content more easily. 

#FamousLastWords
